### ISSUE TITLE
Support for HEIC

### ISSUE THREAD

**Issue by vanerleo** [serverlesspub/imagemagick-aws-lambda-2#11]
any chance of adding support for HEIC format?

**Comment by gojko** [comment]
we don't need it for our purposes, but adding another format should be fairly straight-forward - just add the appropriate library to MakeFile_ImageMagick, similar to here https://github.com/serverlesspub/imagemagick-aws-lambda-2/blob/master/Makefile_ImageMagick#L95 and make it build with that library by appending the lib name here: https://github.com/serverlesspub/imagemagick-aws-lambda-2/blob/master/Makefile_ImageMagick#L125

**Comment by rtcpw** [comment]
I wish this was added to the layer by default. iPhones use HEIC images by default for years.
