### ISSUE TITLE
lambda with imagemagick not working 10.x

### ISSUE THREAD

**Issue by patelmm** [serverlesspub/imagemagick-aws-lambda-2#14]
node 8.10 working fine but when we try to update node version 10.x the getting some errors.

`due to an error: Error: Stream yields empty buffer`

Can you please help me out.

**Comment by gojko** [comment]
hi - in order to help you'll need to provide a bit more context - what you are executing, how, and what you're passing in. creating a minimal executable project that demonstrates the problem would be very beneficial here.

**Comment by patelmm** [comment]
I have setup [lambda function with imagemagic](https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html) its working fine node 8.10 but when i try to convert webp then getting some errors. So i'm finding solution.

**Comment by gojko** [comment]
webp isn't built into this layer by default, you'll need to add the webp library into https://github.com/serverlesspub/imagemagick-aws-lambda-2/blob/master/Makefile_ImageMagick, similarly how png and jpg are added
