### ISSUE TITLE
Python 3.8 is running based on Amazon Linux 2

### ISSUE THREAD

**Issue by GitSumito** [serverlesspub/imagemagick-aws-lambda-2#16]
According to aws official site, 
Python 3.8 is running based on `Amazon Linux 2`.
https://docs.aws.amazon.com/lambda/latest/dg/python-programming-model.html

As of now  in `README.md`, only the name of node.js was stated. what do you think of add `Python 3.8` on README.md?

**Comment by gojko** [comment]
merged with your pull request
