### ISSUE TITLE
Can current AWS Lambda Layer support nodejs 12?

### ISSUE THREAD

**Issue by Bilal-S** [serverlesspub/imagemagick-aws-lambda-2#21]
The current AWS layer as published: 
https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:145266761615:applications~image-magick-lambda-layer

Contains binaries for nodejs 10.x. Could another one be created to support lambda 12.x or does this support also 12.x deployments?

Cheers,
B.

**Comment by gojko** [comment]
the same one will work with node12; it is also based on the Amazon Linux 2 AMI
