### ISSUE TITLE
How to connect this layer with Wand Python package

### ISSUE THREAD

**Issue by WaterKnight1998** [serverlesspub/imagemagick-aws-lambda-2#3]
Hi,

Need to use Wand on AWS Lamdba so I installed wand with pip in a folder and uploaded to a layer. 
However, when i use wand i get next error:
`wand.exceptions.MissingDelegateError: no decode delegate for this image format ' @ error/blob.c/BlobToImage/365`

I found as solution in google that i need your layer to make wand work. How can i make a wand layer work with your imagemagic layer?

Best regards,
WaterKnight

**Comment by DannyAziz** [comment]
Hey, so AWS lambda comes with built-in unless you need Imagemagick 7 or another delegate

**Comment by WaterKnight1998** [comment]
Hey, I read that. I decided to create my own layer as follows.

1. Launched an EC2 Tiny with Ubuntu server 18.04.
2. I executed the following commands:
`cd $HOME 
mkdir -p temp/python 
cd temp/python 
pip install wand -t .
cd .. 
zip -r9 ../wand.zip . `
3. I uploaded this  zip as a layer.

Then when I run next lambda code:
```
import json
import boto3
from PyPDF2 import PdfFileReader, PdfFileWriter
import io
import os
from wand.image import Image


def lambda_handler(event, context):

    s3 = boto3.client('s3')
    
    #Accedo a un fichero del s3, lo leeo entero y lo transformo en un objeto de tipo BytesIO para que lo pueda leer el pdf File reader
    stream = io.BytesIO(s3.get_object(Bucket=os.environ["bucket"], Key=os.environ["rutaArchivo"])['Body'].read())
    
    pdf = PdfFileReader(stream)
    pages = pdf.getNumPages()
    print("number of pages: %i" % pages)
    
    for i in range(pdf.getNumPages()):
        
        output = PdfFileWriter()
        output.addPage(pdf.getPage(i))
        
        tmp = io.BytesIO()
        output.write(tmp)
        tmp.seek(0)
        
        img = Image(file = tmp, resolution = 72)
        img.convert("png")
        
        nombre="paginas/pagina"+str(i)+".png"
        s3.upload_fileobj(img, os.environ["bucket"],nombre )
    
    return {
        'statusCode': 200,
        'body': json.dumps(pages)
    }
```

I get this error:
```
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 29, in lambda_handler
    img = Image(file = tmp, resolution = 72)
  File "/opt/python/wand/image.py", line 8207, in __init__
    self.read(file=file, resolution=resolution, units=units)
  File "/opt/python/wand/image.py", line 8686, in read
    self.raise_exception()
  File "/opt/python/wand/resource.py", line 240, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: no decode delegate for this image format `' @ error/blob.c/BlobToImage/365

END RequestId: 8a4b5fee-721e-4ab7-b882-c8dd8dd786f0
REPORT RequestId: 8a4b5fee-721e-4ab7-b882-c8dd8dd786f0	Duration: 2681.02 ms	Billed Duration: 2700 ms 	Memory Size: 128 MB	Max Memory Used: 101 MB	
```

So as I saw in a website it looks like no Imagemagick was provided by AWS Lambda

**Comment by DannyAziz** [comment]
So the error you are getting is an issue with the PDF format not being supported

In my opinion, the imagemagick that's bundled into Lambda is the one that is being called with your code

**Comment by DannyAziz** [comment]
@stojanovic @simalexan It would be cool if there was a version of this layer that gave a way for us to use ImageMagick's API's with tools like Wand

**Comment by WaterKnight1998** [comment]
> 
> 
> So the error you are getting is an issue with the PDF format not being supported
> 
> In my opinion, the imagemagick that's bundled into Lambda is the one that is being called with your code

What can I do for solving the problem? Any idea?

**Comment by DannyAziz** [comment]
So you need to compile ImageMagick into static binaries and then you need to point wand to those static binaries by using `MAGICK_HOME` 

However, I have been trying this the last few days and have not really got anywhere...

**Comment by WaterKnight1998** [comment]
I haved read that too.
I have tried right now the next code: 
```
with Image() as pdf:
        pdf.format='pdf'
        pdf.read(blob=stream)
    #pdf = Image(format="pdf",blob=stream,resolution=300)
        pdfImage = pdf.convert("jpeg")
        i=1
        for img in pdfImage.secuence:
            page = Image(image=img)
            
            tmp = io.BytesIO()
            tmp.seek(0)
            page.save(file=tmp)
            
            nombre="paginas/pagina"+str(i)+".jpeg"
            s3.upload_fileobj(tmp, os.environ["bucket"],nombre )
```
And throws me the next error:
```
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 37, in lambda_handler
    pdf.format='pdf'
  File "/opt/python/wand/image.py", line 1733, in format
    raise ValueError(repr(fmt) + ' is unsupported format')
ValueError: 'pdf' is unsupported format

END RequestId: 81892afc-a49d-4634-9d99-385ef21b0a93
REPORT RequestId: 81892afc-a49d-4634-9d99-385ef21b0a93	Duration: 2367.02 ms	Billed Duration: 2400 ms 	Memory Size: 128 MB	Max Memory Used: 100 MB	
```

**Comment by gojko** [comment]
@WaterKnight1998 this version of imagemagick does not come with ghostscript, and imagemagick needs ghostscript for PDF support. you will need to modify the [makefile](https://github.com/serverlesspub/imagemagick-aws-lambda-2/blob/master/Makefile_ImageMagick) to compile and include ghostscript libraries if you want pdf support. alternatively, skip over imagemagick, wand and the whole stack and just install ghostscript directly to your Lambda, then convert PDFs using a subprocess

**Comment by WaterKnight1998** [comment]
> @WaterKnight1998 this version of imagemagick does not come with ghostscript, and imagemagick needs ghostscript for PDF support. you will need to modify the [makefile](https://github.com/serverlesspub/imagemagick-aws-lambda-2/blob/master/Makefile_ImageMagick) to compile and include ghostscript libraries if you want pdf support. alternatively, skip over imagemagick, wand and the whole stack and just install ghostscript directly to your Lambda, then convert PDFs using a subprocess

How can i include ghostscript libraries on aws lambda? I found layer for nodejs. However i need it for python3!

**Comment by gojko** [comment]
the layer for nodejs will work for python as well, it's just a linux binary

**Comment by WaterKnight1998** [comment]
So, which layers do i need to make imagemagick work with ghostscript?

How can i use a subprocess to invoke ghostscript? Can you show me any example, pls?

**Comment by gojko** [comment]
@WaterKnight1998 i'm posting this so you know I'm not ignoring you, but you're asking for something requiring far more time than I have to field community github requests. maybe someone else has more time to help, sorry
