### ISSUE TITLE
delegate library support not built-in

### ISSUE THREAD

**Issue by trungegd** [serverlesspub/imagemagick-aws-lambda-2#6]
I just create lambda function and used this layer. But when I add font for text in image, I get an error:

`{ Error: Command failed: convert: delegate library support not built-in '/tmp/fonts/Archer-Bold.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1808.
convert: non-conforming drawing primitive definition 'text' @ error/draw.c/RenderMVGContent/4397.
    at ChildProcess.<anonymous> (/var/task/node_modules/imagemagick/imagemagick.js:88:15)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) timedOut: false, killed: false, code: 1, signal: null }`

My params: -size,863x875,xc:transparent,(,-fill,#231f20,-size,391.8412x245.1814,xc:transparent,-font,/tmp/fonts/Archer-Bold.ttf,-pointsize,22.152,-stroke,none,-draw,gravity center kerning 0 text 0,0 "I love you so",-background,none,-rotate,0.00,),-geometry,+228.4788+551.5006,-composite,/tmp/images/gexqcZl7zU.png

Can you detect for me about to solve it.

**Comment by gojko** [comment]
to keep the layer size small, the default includes a minimal set of libraries, for most common image formats. it does not include freetype, so you'll need to change the [makefile](https://github.com/serverlesspub/imagemagick-aws-lambda-2/blob/master/Makefile_ImageMagick) and add it in. You can probably copy the necessary parts from the https://github.com/serverlesspub/rsvg-convert-aws-lambda-binary layer makefile, since it bundles freetype

**Comment by trungegd** [comment]
He Gojko,

Many thanks for you help. 
Can you help me about create Makefile or document to create Makefile. I don't know about language of Makefile. 

For new features, I want to crop image, create image with font, text or put image into a image,... by using lambda function.

Thanks in advance.

**Comment by lambtron** [comment]
thank you @gojko for putting this together. makes using imagemagick and lambda very easy.

i also need `freetype` in my lambda, and putting it in the layer makes the most sense.

i added the freetype download and installation in the make file, but i'm getting this error when i try `make all` and `make deploy`:

```
MagickCore/annotate.c:89:10: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
          ^~~~~~~~~~~~
compilation terminated.
```

looks like the path isn't set properly for freetype, but i'm at a loss as to what it should be. looks like my [configure variable](https://github.com/lambtron/imagemagick-aws-lambda-2/blob/master/Makefile_ImageMagick#L16) is set correctly.

here is my version:
https://github.com/lambtron/imagemagick-aws-lambda-2/blob/master/Makefile_ImageMagick#L116

and the commit so you can see the changes: https://github.com/lambtron/imagemagick-aws-lambda-2/commit/bbb76bbee296616feecc8b1a146cbcefdc9be6ad

any thoughts as to what might be causing this issue? 

thanks again!!

**Comment by lambtron** [comment]
i got it to work. i copied the entire section from the rsvg including harfbuzz. THANK YOU!

**Comment by trungegd** [comment]
> to keep the layer size small, the default includes a minimal set of libraries, for most common image formats. it does not include freetype, so you'll need to change the [makefile](https://github.com/serverlesspub/imagemagick-aws-lambda-2/blob/master/Makefile_ImageMagick) and add it in. You can probably copy the necessary parts from the https://github.com/serverlesspub/rsvg-convert-aws-lambda-binary layer makefile, since it bundles freetype

Here is my Makefile_ImageMagick file:

[Makefile_ImageMagick.txt](https://github.com/serverlesspub/imagemagick-aws-lambda-2/files/3844453/Makefile_ImageMagick.txt)


@gojko Thanks so much. It works fine for me.

**Comment by jugglingcats** [comment]
@lambtron or @trungegd would you be willing to post your layer so others can use it? I need freetype and I'm sure others would benefit.

**Comment by jugglingcats** [comment]
@trungegd am trying to use your make file (on Ubuntu with Docker installed) but get the following error:

```
/var/task/build/fontconfig-2.13.0/missing: line 81: gperf: command not found
WARNING: 'gperf' is missing on your system.
         You might have modified some files without having the proper
         tools for further handling them.  Check the 'README' file, it
         often tells you about the needed prerequisites for installing
         this package.  You may also peek at any GNU archive site, in
         case some other package contains this missing 'gperf' program.
```

Tried installing on the host Ubuntu but same error so I assume this is missing in Docker...?

Thanks.

**Comment by trungegd** [comment]
@jugglingcats I used to see this error but then I added gperf installation to make file and it worked.

`## dev tool istallation

init:
	yum install -y gcc gcc-c++ cmake3 intltool flex bison shared-mime-info gperf`

**Comment by thecfguy** [comment]
Here is compiled one if someone do not want to go with process of building up [Imagemagick.zip](https://drive.google.com/a/thecfguy.com/file/d/1m71kJL8qe_SNtVANlfsdy8JP0PkQ70wj/view?usp=sharing)

Thanks @trungegd @jugglingcats @gojko

**Comment by edjames** [comment]
Hi. 

Sorry to open old wounds, but I'm having real problems trying to get freetype included in my build.
I've tried the following:

- manually including the various parts in the `Makefile_ImageMagick` from this linked project: https://github.com/serverlesspub/rsvg-convert-aws-lambda-binary
- using the `Makefile_ImageMagick` provided by @lambtron 
- using the `Makefile_ImageMagick` provided by @trungegd 
- using the compiled zip release provided by @thecfguy 

Unfortunately I keep getting the same error in all cases:

```
MiniMagick::Invalid: `/opt/bin/magick identify /tmp/mini_magick20201021-9-od9shb.pdf` failed with error:
/opt/bin/magick: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/bin/magick)
```

Not sure if the host system makes a difference when compiling here (given it's done in a Docker container) but for what it's worth I'm on a Mac running Catalina 10.15.7

Can anyone help please?
