### ISSUE TITLE
Issues calling convert (and other commands) in "sam local" environment

### ISSUE THREAD

**Issue by hburrows** [serverlesspub/imagemagick-aws-lambda-2#9]
Great work and thank you.  This repo is very well done and perfect for my needs.

I've got one issue I'm stumped by, however.  I use AWS SAM and for local development, I use `sam local invoke ...` and `sam local start-lambda ...` for development and testing. When running in these environments calls to `convert`, `identity`, etc. fail with:

```
Usage: magick tool [ {option} | {image} ... ] {output_image}
Usage: magick [ {option} | {image} ... ] {output_image}
       magick [ {option} | {image} ... ] -script {filename} [ {script_args} ...]
       magick -help | -version | -usage | -list {option}
```

When running on AWS it works fine so it's something limited to `sam local`

In the following Node example, the first call will return  the above stdout and the second (calling magick directly) returns the expected output.

Calling `/opt/bin/convert`:
```
import { exec } from 'child_process';
const promiseExec = util.promisify(exec);

const { stdout } = await promiseExec('/opt/bin/convert -version');
```
returns:
```
Usage: magick tool [ {option} | {image} ... ] {output_image}
Usage: magick [ {option} | {image} ... ] {output_image}
       magick [ {option} | {image} ... ] -script {filename} [ {script_args} ...]
       magick -help | -version | -usage | -list {option}
```
Calling `/opt/bin/magick`:
```
import { exec } from 'child_process';
const promiseExec = util.promisify(exec);

const { stdout } = await promiseExec('/opt/bin/magick -version');
```
returns:
```
Version: ImageMagick 7.0.8-68 Q16 x86_64 2019-11-19 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib jng jp2 jpeg png tiff webp zlib
```

The only thing I can figure is that it has something to do with the symlink of `convert -> magick`.  

Do you have any ideas about why this might not be working and how to remedy it?

**Comment by hburrows** [comment]
I deployed this layer verbatim directly from the serverlessrepo (https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:145266761615:applications~image-magick-lambda-layer) and I get the exact same results.

Is it the case that this layer does not work when running in a `sam local` environment?

That would be really unfortunate because it makes development slow and difficult.

**Comment by hburrows** [comment]
Looks like https://github.com/awslabs/aws-sam-cli/issues/878 is the culprit.  Fingers crossed this will get fixed in the not too distant future.

**Comment by gojko** [comment]
i'm closing this as it's a problem to be fixed with sam, not with this project

**Comment by charlie-s** [comment]
@hburrows were you ever able to resolve this? We're stuck on the imagemagick layer as well. Suppose we could put calls to image magick in a separate js module so that we can still test locally.
